local_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05 

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0